# Build
docker build -t udagram-api-feed ./udagram-api-feed
docker build -t udagram-frontend ./udagram-frontend
docker build -t udagram-api-user ./udagram-api-user
docker build -t reverseproxy ./reverseproxy

# Tagging
docker tag udagram-api-feed sudkul/udagram-api-feed:v1
docker tag udagram-frontend sudkul/udagram-frontend:v1
docker tag udagram-api-user sudkul/udagram-api-user:v1
docker tag reverseproxy sudkul/reverseproxy:v1

#Push
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push sudkul/udagram-api-feed:v1
